### PR TITLE
Stages and deploy support

### PR DESCRIPTION
**Pull request by deepbrook**
As mentioned in #30, the repo could do with some automated building.

I have add this support to the `.travis.yml` file. I have also added the us of `build stages`, which makes use of concurrent execution of jobs, which may help improve the speed of CI checks.

the `Deploy` stage executes only for python 3.6, and creates a `bdsit_wheel`, which I believe to be universally installable. Correct me if I'm wrong here, I'm not well read on the differences of the distributions.

In order to avoid building and pushing to `pypi` on every push, the conditional `tags: true` was added - that way, it is only built if you push a tagged commit. 

The password for pypi should be encrypted using the `travis CLI` - since I'm guessing you won't want to share your pypi password with the world ;) see here for more information about this: 
https://docs.travis-ci.com/user/deployment/pypi/

Let me know what you think!

### CODE REVIEW

**Comment by deepbrook** [comment]
Hm. The build matrix isn't generated correctly (there should be a separate job running for each version of python in `Testing`). I will have a look into this.

**Comment by deepbrook** [comment]
I've asked the good people of [stackoverflow,](https://stackoverflow.com/questions/47453613/jobs-in-build-stage-not-expanding-as-expected) to see what they say about this.

update: Question deleted, answer found [here](https://stackoverflow.com/questions/44514781/whats-a-sane-way-to-define-custom-travis-job?rq=1)

**Comment by deepbrook** [comment]
All fixed up. Should work now, as expected. Of course, it remains to see if the deploy process works correctly - but you'd have to test this, since it requires a tag to be pushed to the repository.

**Review by aayush26 — COMMENTED** [review]
Can you exclude files:
handlers.py
models.py
urlbuilder.py
from this commit since its a part of the last PR. Just to avoid unnecessary merge conflicts.

**Comment by deepbrook** [comment]
I branched this off PR #31, since I figured you'd merge that one before this. 

But if you tell me how I can go about excluding them from this PR, I'll get right on it! Or do I need to submit a new PR for that to work ? That might actually be easier.

**Pull request closed without merging**
